# Generated by Django 3.2.3 on 2021-05-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_name_userbase_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
