# Generated by Django 3.2.3 on 2021-05-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
